"""Visual constants for the Rxplain PDF template.

Colours are taken from the Rxplain website (Tailwind teal/slate/amber palette).
If the official reference PDF differs, adjust the values here: every other module
reads from this file, so branding changes never require touching layout code.
"""
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm

PACKAGE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = PACKAGE_DIR / "assets"
FONTS_DIR = PACKAGE_DIR / "fonts"

RXPLAIN_LOGO = ASSETS_DIR / "rxplain_logo.png"
TRIMITHA_LOGO = ASSETS_DIR / "T.png"      # navy tile with cyan triangle + white T (supplied by the owner)

# ---- Brand text ---------------------------------------------------------
BRAND_NAME = "Rxplain"
BRAND_TAGLINE = "Making Medical Terms Simple"
POWERED_BY = "Powered by"
POWERED_BY_BRAND = "Trimitha"
FOOTER_LEFT_TEXT = "rxplain.vercel.app"
FOOTER_LEFT_URL = "https://rxplain.vercel.app"
FOOTER_RIGHT_TEXT = "trimitha.co.in"
FOOTER_RIGHT_URL = "https://trimitha.co.in"

# ---- Palette ------------------------------------------------------------
TEAL_700 = colors.HexColor("#0F766E")
TEAL_600 = colors.HexColor("#0D9488")
TEAL_100 = colors.HexColor("#CCFBF1")
TEAL_50 = colors.HexColor("#F0FDFA")
SLATE_900 = colors.HexColor("#0F172A")
SLATE_800 = colors.HexColor("#1E293B")
SLATE_700 = colors.HexColor("#334155")
SLATE_500 = colors.HexColor("#64748B")
SLATE_400 = colors.HexColor("#94A3B8")
SLATE_300 = colors.HexColor("#CBD5E1")
SLATE_200 = colors.HexColor("#E2E8F0")
SLATE_50 = colors.HexColor("#F8FAFC")
RED_700 = colors.HexColor("#B91C1C")
RED_200 = colors.HexColor("#FECACA")
RED_50 = colors.HexColor("#FEF2F2")
AMBER_800 = colors.HexColor("#92400E")
AMBER_600 = colors.HexColor("#D97706")
AMBER_200 = colors.HexColor("#FDE68A")
AMBER_50 = colors.HexColor("#FFFBEB")
BLUE_700 = colors.HexColor("#1D4ED8")
BLUE_100 = colors.HexColor("#DBEAFE")
BLUE_50 = colors.HexColor("#EFF6FF")
# Deep navy peacock blue: border around the Trimitha logo (top-right corner of the header)
PEACOCK_NAVY = colors.HexColor("#0B3C5D")
SHOW_TRIMITHA_LOGO = False   # True = show assets/T.png (with the navy border) next to "Powered by Trimitha"
TRIMITHA_BORDER_W = 2.0  # points

# ---- Page geometry (A4 portrait) ---------------------------------------
PAGE_SIZE = A4
PAGE_W, PAGE_H = PAGE_SIZE
MARGIN_X = 16 * mm
CONTENT_W = PAGE_W - 2 * MARGIN_X

HEADER_H = 27 * mm          # branded header band (logo row + rule)
CONT_BAND_H = 9 * mm        # "Patient: ..." strip under header (pages 2+)
FOOTER_H = 15 * mm
FRAME_TOP = HEADER_H + CONT_BAND_H + 2 * mm      # distance page-top -> content
FRAME_BOTTOM = FOOTER_H + 4 * mm                 # distance page-bottom -> content

# ---- Type scale (large, elderly-friendly) -------------------------------
BODY_SIZE = 11
BODY_LEADING = 16.5
SMALL_SIZE = 9.5
TABLE_SIZE = 10
TABLE_HEAD_SIZE = 8.5
H1_SIZE = 21
H2_SIZE = 14.5

# ---- Static (non-AI) wording; override via `labels=` ---------------------
DEFAULT_LABELS = {
    "report_title": "Medical Summary",
    "patient_name": "Patient Name",
    "age": "Age",
    "date": "Report Date",
    "language": "Language",
    "summary": "Summary",
    "terms": "Key Medical Terms",
    "term_col": "Medical Term",
    "meaning_col": "What it means",
    "warnings": "Critical Warnings",
    "schedule": "Medicine Schedule",
    "col_medicine": "Medicine",
    "col_type": "Type",
    "col_purpose": "Purpose & Instructions",
    "col_morning": "Morning",
    "col_afternoon": "Afternoon",
    "col_night": "Night",
    "col_duration": "Duration",
    "lbl_purpose": "Purpose:",
    "lbl_timing": "Timing:",
    "lbl_side_effects": "Side effects:",
    "checklist": "Your Action Plan",
    "notes": "Important Notes",
    "follow_up": "Follow Up",
    "diet": "Diet & Recovery Plan",
    "diet_goal": "Goal:",
    "diet_eat": "Foods to Eat",
    "diet_avoid": "Foods to Avoid",
    "diet_hydration": "Hydration:",
    "diet_tips": "Daily Tips",
    "continued": "Patient:",
    "page": "Page",
    "of": "of",
    # Static safety text, wording taken from the Rxplain website.
    "disclaimer_title": "Please Note:",
    "disclaimer_body": (
        "Rxplain is an AI tool designed to help you understand medical documents. "
        "It does not replace a doctor or give medical advice. Always rely on your "
        "healthcare professional for treatment decisions."
    ),
    "reminder": (
        "Remember: This summary is generated by AI to help you understand better, "
        "but always keep the original document for your doctor's reference."
    ),
}
